#!/bin/sh
fluent3DMeshToFoam *.msh -scale 0.205
splitMeshRegions -cellZones -overwrite
rm -r 0*/solidVolume/{mut,alphat,k,p,U,omega,G,epsilon}
rm -r 0*/fluidVolume/{cp,K,rho}
for i in fluidVolume solidVolume
do
    changeDictionary -region $i
    paraFoam -touch -region $i
done
rm -rf processor*
for i in fluidVolume solidVolume
do
   paraFoam -touch -region $i
done