#!/bin/sh
fluent3DMeshToFoam *.msh -scale 0.205
splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
rm -f 0*/solidVolume/{mut,alphat,epsilon,k,p_rgh,p,U,omega,G,H2O,N2,O2}

# remove solid fields from fluid regions (important for post-processing)
for i in fluidVolume
do
   rm -f 0*/$i/{cp,K,rho}
done

for i in fluidVolume solidVolume
do
   changeDictionary -region $i
done


#-- Run on single processor
#runApplication chtMultiRegionFoam

# Decompose
#for i in fluidVolume solidVolume
#do
#  decomposePar -region $i
#done

# Run
#mpirun -np 2 porousIterativeMultiregionFoam -parallel
#porousIterativeMultiregionFoam
# Reconstruct
#for i in fluidVolume solidVolume
#do
#   reconstructPar -region $i
#done


echo
echo "creating files for paraview post-processing"
echo
for i in fluidVolume solidVolume
do
   paraFoam -touch -region $i
done

# -----------------------------------------------------------------------------
